name: Docker Image CI

env:
  docker_registry: pnksh
  docker_repo: 'octopus-webhook'

on:
  release:
    types: [published]

jobs:
  unittest:
    runs-on: ubuntu-latest

    services:
      testmongo:
        image: mongo:4.4
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: secret
        ports:
          - 27017:27017

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create network in docker
      run: |
        docker network create test
        docker network ls
        
    - name: Spin mongodb up
      run: |
        docker run -d --network=test --name testmongo -e 'MONGO_INITDB_ROOT_USERNAME=admin' -e 'MONGO_INITDB_ROOT_PASSWORD=secret' mongo:4.4
        
    - name: Run unittest
      run: |
        docker build -f .docker/unittest/Dockerfile -t unittest .
        docker run --rm --network=test \
        -e 'MONGO_HOST=mongodb://admin:secret@testmongo:27017/octopus-webhook?authSource=admin' \
        -e 'BASIC_AUTH_USER=admin' \
        -e 'BASIC_AUTH_PASS=secret' \
        unittest

  docker_build_push:
    needs: unittest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      id: docker_build
      run: docker build -f .docker/Dockerfile -t ${{ env.docker_registry }}/${{ env.docker_repo }}:latest -t ${{ env.docker_registry }}/${{ env.docker_repo }}:${{ github.event.release.tag_name }} .

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to DockerHub
      run: |
        docker push ${{ env.docker_registry }}/${{ env.docker_repo }}:latest
        docker push ${{ env.docker_registry }}/${{ env.docker_repo }}:${{ github.event.release.tag_name }}