name: Verify unittest

on:
  push:
    branches: [main]

jobs:
  unittest:
    runs-on: ubuntu-latest

#    services:
#      testmongo:
#        image: mongo:4.4
#        env:
#          MONGO_INITDB_ROOT_USERNAME: admin
#          MONGO_INITDB_ROOT_PASSWORD: secret
#        ports:
#          - 27017:27017

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create network in docker
      run: |
        docker network create test
        docker network ls
        
    - name: Spin mongodb up
      run: |
        docker run -d --network=test --name testmongo \
        -e AUTH=yes \
        -e MONGODB_ADMIN_USER=admin \
        -e MONGODB_ADMIN_PASS=secret \
        -e MONGODB_APPLICATION_DATABASE=mytestdatabase \
        -e MONGODB_APPLICATION_USER=testuser \
        -e MONGODB_APPLICATION_PASS=testpass \
        aashreys/mongo-auth:latest

    - name: Run unittest
      run: |
        docker build -f .docker/unittest/Dockerfile -t unittest .
        docker run --rm --network=test -e 'MONGO_DATABASE=mytestdatabase' -e 'MONGO_HOST=testmongo' -e 'MONGO_PORT=27017' -e 'MONGO_USERNAME=admin' -e 'MONGO_PASSWORD=secret' -e 'MONGO_AUTH_SOURCE=admin' -e 'MONGO_MECHANISM=SCRAM-SHA-1' unittest