name: Verify unittest

on:
  push:
    branches: [main]

jobs:
  unittest:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: secret
        ports:
          - 27017:27017

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run unittest
      env:
        MONGO_DATABASE: octopus-webhook
        MONGO_HOST: mongo
        MONGO_PORT: 27017
        MONGO_USERNAME: admin
        MONGO_PASSWORD: secret
        MONGO_AUTH_SOURCE: admin
        MONGO_MECHANISM: SCRAM-SHA-1
      run: |
        docker build -f .docker/unittest/Dockerfile -t unittest .
        docker run --rm --network-host unittest